### ISSUE TITLE
Article Metering

### ISSUE THREAD

**Issue by whaleen** [Pirate-Wires/pirate-wires#117]
# Article Limit for Unpaid Users

Limit unpaid users to 3 articles. XX day grace period for lapsed subscribers.  

## Tasks

- [x] Create Supabase table to store view counts  
```
CREATE TABLE article_metering (
    cookie_id UUID PRIMARY KEY,
    viewed_articles BIGINT[],
    view_counts JSONB,
    ip_addresses INET[],
    last_accessed_at TIMESTAMPTZ
);
```

- [x] Create API 

```
// /api/article-metering/route.ts
```

- [ ] Increment view count when serving articles

```
async function recordArticleView(userId: string, ip: string) {

  await supabase('increment_article_views', {
    user_id: userId, 
    ip_address: ip  
  })

}
```

- [ ] Check limits before displaying articles

```
async function checkViewLimit(userId: string) {

  const { sum_views } = await supabase
    .from('user_ip_articles')
    .select(sum('view_count'), 'user_id')
    .eq('user_id', userId)  
    .single();

  return sum_views;
}
```

- [ ]  Handle grace period display & messaging

---

## Initial requirements summary:

> 1. In `components/remainingArticleEls.tsx` (which is dropped into `app/(website)/p/[slug]/default.tsx`) there are two variables, `showRemainingArticles` and `showNoMoreArticles`
> 2. If the user is logged in and subscribed, both of those variables should remain false
> 3. If the user is not logged in, or is logged in and not subscribed, we will need to check the IP address against our database of IP addresses, and how many free articles they have read (limit of 3)
> 4. If they've read 3, set `showNoMoreArticles` to true. If they've read less than three, set `showRemainingArticles` to true and dynamically update the number of articles remaining (3 - # of articles read)
