### ISSUE TITLE
Domain Name Switch / Launch Day Checklist 

### ISSUE THREAD

**Issue by whaleen** [Pirate-Wires/pirate-wires#160]
- [ ] Inventory all places where URLs must be changed. Document.
- [ ] Use env vars in all places possible in code base pointing to vercel app subdomain instead of top level domain piratewires.com
- [ ] Document again. All hands scrutinize that **launch day process**. _Document yet again._
